version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    build:
      context: "."
      dockerfile: "db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: donut_catch
    volumes:
      - donut-catch-data:/var/lib/postgresql/data
volumes:
  donut-catch-data:
    external: true
